### ISSUE TITLE
Report energy estimate (and RSRP)

### ISSUE THREAD

**Issue by coderbyheart** [hello-nrfcloud/firmware#105]
The current shadow does not include EEST, nor RSRP: https://github.com/hello-nrfcloud/proto-map/blob/5eba224f67c8a96bded33bfb3d59b4dc769cb0f9/lwm2m/14203.xml#L81-L90

```json
{
  "networkInfo": {
    "currentBand": 20,
    "supportedBands": "(1,2,3,4,5,8,12,13,18,19,20,25,26,28,66,85)",
    "areaCode": 33131,
    "mccmnc": "24201",
    "ipAddress": "10.108.72.99",
    "ueMode": 2,
    "cellID": 51297540,
    "networkMode": "LTE-M GPS"
  }
}
```

**Comment by balaji-nordic** [comment]
I did a change to report RSPR. To test my change, I tried to revert it and see if RSRP does not get reported to the cloud. But I see that the UI shows RSRP even if I revert my change.

![image](https://github.com/hello-nrfcloud/firmware/assets/41895435/b066f154-da73-4aa2-97ae-076b9aee0371)

Could it be a cached value? Or perhaps I am looking at the wrong place?

**Comment by coderbyheart** [comment]
No, the old value will be shown.

**Comment by coderbyheart** [comment]
dBM should be negative
