### ISSUE TITLE
Run-time configuration

### ISSUE THREAD

**Issue by coderbyheart** [hello-nrfcloud/firmware#110]
> [!NOTE]  
> Here is the proposal for the run-time configuration of the firmware that has been agreed on with PMT.

Defaults:
- GNSS disabled (most users are inside when trying out the device)
- Neighboring cell measurements + WiFi enabled
- Cloud update interval: 3600 seconds

Users can put the device in a temporary real-time mode
1. by pressing the button
   - Button press is reported to cloud 
1. by (re-)booting the device

In the temporary real-time mode:
1. Device changes update interval to 10 seconds for 10 minutes
   - if button is pressed within that time, timer is reset to 10 minutes
   - if device receives message from cloud (e.g. change LED state) timer is reset
1. After the timer expires, the device falls back to previously configured update interval

Users can configure (through the shadow):
- GNSS (on/off)
- Cloud update interval (in seconds)

> [!TIP]
> The Firmware can use a higher update interval than what is desired by the user if required (e.g. if GNSS is enabled update interval of 1 second is not possible)

**Comment by jhn-nordic** [comment]
WiFi location. Is that considered as "cell location" or should we have a separate config for that

**Comment by coderbyheart** [comment]
Yes, clarified that WiFi location is included in Neighboring cell measurements.

We discussed to give the users the option to enable/disable NCELL or WiFi site survey but decided that this is not useful in the context of the out-of-box experience.

**Comment by coderbyheart** [comment]
LwM2M object 14310 is defined for this: https://github.com/hello-nrfcloud/proto-map/blob/f2e973038bb05e1cef38011e8e36cb597d480a42/lwm2m/14301.xml

**Comment by simensrostad** [comment]
Config and LED object can now be set. Temporary real-time mode still needs implementation.
