### ISSUE TITLE
Use LED to show current state to user

### ISSUE THREAD

**Issue by coderbyheart** [hello-nrfcloud/firmware#206]
- [ ] Blink LED yellow while searching for cellular connection: https://nordicsemi.atlassian.net/browse/CIA-1269
- [x] Blinking blue LED while in real-time mode
- [x] Show user LED color
- [x] Document LED behaviour

## LED state diagram

![Thingy out-of-box experience 2024 - OOB firmware LED state diagram](https://github.com/hello-nrfcloud/firmware/assets/188915/36fa4d85-4701-4abe-8c41-a37d27606599)

Source: https://miro.com/app/board/uXjVPN9ZHeQ=/?moveToWidget=3458764593923387145&cot=14

**Comment by balaji-nordic** [comment]
Tip: Look at the LED implementation of ATv2 in NCS 1.8 (pre-CAF)

**Comment by simensrostad** [comment]
1.8 is the last release without CAF. led_module

**Comment by simensrostad** [comment]
The scheduling functionality to queue led patterns is a part of NCS 2.0.0 so there will have to be mix

**Comment by simensrostad** [comment]
This is typically how you can queue up led patterns.

		transition_list_clear();
		transition_list_append(LED_STATE_CLOUD_PUBLISHING, 5);
		transition_list_append(LED_STATE_ACTIVE_MODE, 5);
		transition_list_append(LED_STATE_GNSS_SEARCHING, HOLD_FOREVER);
		k_work_reschedule(&led_pattern_update_work, K_NO_WAIT);

**Comment by simensrostad** [comment]
https://github.com/nrfconnect/sdk-nrf/tree/v1.5-branch/applications/asset_tracker_v2/src/led
This is how we can set led patterns, files needed are included in these files

**Comment by coderbyheart** [comment]
Added the state diagram.

**Comment by simensrostad** [comment]
Done, please reopen if behavior is not satisfied.

**Comment by coderbyheart** [comment]
I've added a new issue instead: https://github.com/hello-nrfcloud/firmware/issues/246
