### ISSUE TITLE
Wrong version reported in Memfault

### ISSUE THREAD

**Issue by coderbyheart** [hello-nrfcloud/firmware#209]
A device that is running `v2.0.0-preview.12` shows up like this in Memfault:

![image](https://github.com/hello-nrfcloud/firmware/assets/188915/007f0592-7d35-40bc-8276-23cfe4b7f122)

https://app.memfault.com/organizations/nordic-semiconductor-asafbpk/projects/hello-nrfcloud-com/devices/355025930003841

This results in the version not being matched to the correct release and symbol file.

**Comment by coderbyheart** [comment]
Cannot confirm that this works.

![Screenshot_20240628_130925](https://github.com/hello-nrfcloud/firmware/assets/188915/285ee318-5402-4033-8183-a04e49f2ee7b)
![Screenshot_20240628_130947](https://github.com/hello-nrfcloud/firmware/assets/188915/305dc363-04fb-4fa6-b982-a5f1a9ed9742)

**Comment by simensrostad** [comment]
![image](https://github.com/hello-nrfcloud/firmware/assets/42843330/ed8f762f-458c-453e-ac06-60b07a16a60a)

Seems that new builds are added under the wrong type in memfault
