### ISSUE TITLE
Add LED state for location search

### ISSUE THREAD

**Issue by coderbyheart** [hello-nrfcloud/firmware#246]
Right now (v19) the LED is blinkling blue while the device is searching for location.

According to the docs, this means it is "Device is actively polling cloud", which is of course, not correct.

Introduce a new LED color (e.g. blinking green) to signal that location search is ongoing.

**Comment by simensrostad** [comment]
"Technically" we are polling cloud at the same time as we are obtaining location. Polling occurs every 20 seconds in the temporary _real-time mode_, location searches occurs in between (triggered at the same time). However, when GNSS is enabled some scew is expected if GNSS hasn't finished before the next poll.

Not sure if this info is helpful in this issue, I just wanted to provide some context. Anyway I think it would be nice to show some LED pattern when we are searching for location. Although I expect the pattern to be rather short when GNSS is disabled.

We also need to accommodate for the user set LED configuration. I suggest that the user configured LED is shown as long as its a valid color.

If its off (0,0,0), we show the other patterns, active polling, location search etc...
When the temporary real time mode duration (10 min) is up LEDS are disabled, and UART for that matter. To go into the lowest powered state. We already have preexisting tasks for this.

**Comment by coderbyheart** [comment]
> We also need to accommodate for the user set LED configuration. I suggest that the user configured LED is shown as long as its a valid color.
> 
> If its off (0,0,0), we show the other patterns, active polling, location search etc... When the temporary real time mode duration (10 min) is up LEDS are disabled, and UART for that matter. To go into the lowest powered state. We already have preexisting tasks for this.

It think this is a good idea. If user LED color is set to something other than 0,0,0 (RGB) we show the "operation LED state".

**Comment by coderbyheart** [comment]
Fixed via #250
