### ISSUE TITLE
Wireless Logic SIMs not connecting

### ISSUE THREAD

**Issue by Lenakh97** [hello-nrfcloud/firmware#251]
Our Wireless Logic SIMs are not connecting. Reached out to Wireless Logic support and got the following response:

> Please can you ensure you are configuring your device with the below APN details: 
>  
> APN = `eapn1.net` 
> Username/Password = `NordicSe`
> Authentication Type = `PAP` 
>  
> Please can you also advise on the device make and model if provided by WL?
>  
> As well as confirming if the devices have roaming enabled?
>  
> Once the above is confirmed we can further investigate the problems your are facing with your SIMs.

**Comment by coderbyheart** [comment]
Wireless Logic SIMs can be detected using the ICCID prefix `894446`

**Comment by maxd-nordic** [comment]
I tried to connect with these KConfigs, but to no avail:
```
CONFIG_PDN=y
CONFIG_PDN_DEFAULTS_OVERRIDE=y
CONFIG_PDN_DEFAULT_APN="eapn1.net"
CONFIG_PDN_DEFAULT_USERNAME="NordicSe"
CONFIG_PDN_DEFAULT_PASSWORD="NordicSe"
CONFIG_PDN_DEFAULT_AUTH_PAP=y
```

ICCID: 89444611503500007362

**Comment by Lenakh97** [comment]
Got the following answer from support now:

>I have checked at network level and can confirm the following:
>SIM 89444611503500007362 has successfully registered on the Telenor Norway network on 17 July 2024 at 12:38 pm.
>SIM 89444611503500008733 has not had any registration attempts.

**Comment by Lenakh97** [comment]
They followed up with this today:

>As we are unable to see an immediate reason as to why you are experiencing this issue, we are going to be handing over to our specialist Service Support team to investigate further. 
> 
>The team may require more information and therefore any additional details you can provide in advance would be gratefully appreciated. For example:
>· Has the SIM ever worked:
>If yes, when did the SIM stop working/when did the issue first start?
>· Has there been any recent changes made to the device? (e.g. firmware, software, configurations, etc)
>· What is the expected behaviour of the SIM/device?
>· Are there any error messages being returned on the device?
>· Has the SIM been tested in another known working device? 
>If so, what was the outcome?
>If not, can this be actioned? (Ensuring the correct APN is configured for issues with data).
>· Device logs? (If applicable)
> 
>A member of the team will be in touch soon.

I guess the answer to the first question is no, but I'm not sure about the rest.

**Comment by coderbyheart** [comment]
> Has the SIM ever worked:
No.
> Has there been any recent changes made to the device? (e.g. firmware, software, configurations, etc)
This is a new project.
>  What is the expected behaviour of the SIM/device?
It connects and data can be used.
> Are there any error messages being returned on the device?
No.
> Has the SIM been tested in another known working device?
Yes, same result.
> Device logs? (If applicable)
We have provided a modem trace.

**Comment by coderbyheart** [comment]
This should be solved now, will test again later.

**Comment by maxd-nordic** [comment]
should work
