### ISSUE TITLE
Environment values reported as all 0

### ISSUE THREAD

**Issue by coderbyheart** [hello-nrfcloud/firmware#259]
```json
{
      "importId": "01J4BPVJ9GT6J0YPFDNEBH0JVA",
      "timestamp": "2024-08-03T08:49:16.592Z",
      "success": true,
      "senML": [
        {
          "n": "0",
          "v": 0,
          "bn": "14205/0/",
          "bt": 1722674954
        },
        {
          "n": "1",
          "v": 0
        },
        {
          "n": "2",
          "v": 0
        },
        {
          "n": "10",
          "v": 0
        }
      ],
      "lwm2m": [
        {
          "ObjectID": 14205,
          "Resources": {
            "0": 0,
            "1": 0,
            "2": 0,
            "10": 0,
            "99": 1722674954
          }
        }
      ]
    }
```

This happens with https://github.com/hello-nrfcloud/firmware/releases/tag/v2.0.0-preview21

**Comment by coderbyheart** [comment]
Later the devices reports the actual values correctly, so this seems to be a bug related to a reboot.

```json
{
      "importId": "01J4BQ5PNVNZT4MQ39CVRM30AB",
      "timestamp": "2024-08-03T08:54:48.763Z",
      "success": true,
      "senML": [
        {
          "n": "0",
          "v": 28.166849,
          "bn": "14205/0/",
          "bt": 1722675285
        },
        {
          "n": "1",
          "v": 35.463821
        },
        {
          "n": "2",
          "v": 999.66945312
        },
        {
          "n": "10",
          "v": 83
        }
      ],
      "lwm2m": [
        {
          "ObjectID": 14205,
          "Resources": {
            "0": 28.166849,
            "1": 35.463821,
            "2": 999.66945312,
            "10": 83,
            "99": 1722675285
          }
        }
      ]
    }
```

**Comment by balaji-nordic** [comment]
This happened many times on my Thingy91x last week. I reported that to @maxd-nordic  and @jhn-nordic . We believed it was related to the sensor misbehaving. 

Here's what happened to my device. 

It first started to report 45 degrees when I took it outdoors and kept it under the sun for a while. After that, when I took it back indoors, it reported all zeros. Later I took it back outdoors to and that made it work again. Seems like this is something to do with the BSEC library or the sensor hardware perhaps.

**Comment by coderbyheart** [comment]
Given that you know the sensor may misbehave, how about making a check that if all values are 0, to not send it, because this can never be the case with real data.

**Comment by simensrostad** [comment]
Fix https://github.com/hello-nrfcloud/firmware/pull/271

**Comment by simensrostad** [comment]
New fix in the pipeline, had to revert to low power mode from ULP. However this imposes extra current consumption.
@jhn-nordic is looking into a fix for this.
