### ISSUE TITLE
Implement sending the new battery percentage

### ISSUE THREAD

**Issue by coderbyheart** [hello-nrfcloud/firmware#4]
The firmware currently sends the VOLTAGE:

```json
{
  "appId": "VOLTAGE",
  "messageType": "DATA",
  "ts": 1687786221598,
  "data": "3661"
}
```

**Comment by maxd-nordic** [comment]
already implemented: https://github.com/hello-nrfcloud/firmware/blob/03eae86e34dd0f712ef1d15c584550c9b0a10ec7/asset_tracker_v2/src/cloud/cloud_codec/nrf_cloud/json_protocol_names_nrf_cloud.h#L30
