### ISSUE TITLE
[senML] No base-time defined

### ISSUE THREAD

**Issue by coderbyheart** [hello-nrfcloud/firmware#95]
The firmware publishes the following SenML message

```javascript
[
  { '0': '0', '2': 23.4827, '-2': '14205/0/' },
  { '0': '1', '2': 27.921825 },
  { '0': '2', '2': 100683.617187 },
  { '0': '10', '2': 163 },
  { '0': '99', '2': 1716497015439n }
]
```

which has no time defined on the first record. [SenML however requires all records to have a timestamp](https://www.rfc-editor.org/rfc/rfc8428.html#section-4.5.3).

Solution: Define a base time for all records:

```javascript
[
  { '0': '0', '2': 23.4827, '-2': '14205/0/', '-3': 1716497015439n },
  { '0': '1', '2': 27.921825 },
  { '0': '2', '2': 100683.617187 },
  { '0': '10', '2': 163 }
]
```

In our case the record for the resource `99` can be omitted, because it is inferred from the base time.

As [a rule](https://github.com/hello-nrfcloud/proto-map?tab=readme-ov-file#senml-rules):

> Timestamps are to be expressed in the base time property `bt` and are mapped to the LwM2M object's timestamp property and must not be send as a property.

**Comment by maxd-nordic** [comment]
Would this work? https://github.com/hello-nrfcloud/firmware/pull/96

**Comment by coderbyheart** [comment]
Yes.
